version: '3.8'

services:
  frontend:
    build: ./movie-recommender-frontend
    ports:
      - "4200:4200"
    networks:
      - movie-recommender-network

  backend-java:
    build: ./movie-recommender-backend
    ports:
      - "8080:8080"
    networks:
      - movie-recommender-network
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/users_db
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_TMDB_API_KEY=bc35e858027b809c7fd3ea832887e779
      - SPRING_TMDB_BEARER_TOKEN=eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJiYzM1ZTg1ODAyN2I4MDljN2ZkM2VhODMyODg3ZTc3OSIsIm5iZiI6MTcyMzU2NTc5MC4zMjc4MDQsInN1YiI6IjY2YmI3Zjc1ZDVjODY5MDU1ZGE1Y2EzOCIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.KNvtApnkWCn_9qESDzb9ZHlYYH5SHm_h-14nzxvr9FE
      - SPRING_APIURL_PYTHON=http://backend-python:5000

  backend-python:
    build: ./movie-recommender-python
    volumes:
      - ./movie-recommender-python/data/movies_datasets:/app/data/movies_datasets
    ports:
      - "5000:5000"
    networks:
      - movie-recommender-network
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://admin:admin@db:5432/users_db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: users_db
    ports:
      - "5432:5432"
    networks:
      - movie-recommender-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d users_db"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  movie-recommender-network:

volumes:
  postgres_data:
